import type { Metadata } from 'next'
import './globals.css'
import MobileBoundary from '@/components/mobile-boundary'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html>
      <body>
        <MobileBoundary>{children}</MobileBoundary>
      </body>
    </html>
  )
}
